runtime: java17
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.80
  min_instances: 1
  max_instances: 30
  max_concurrent_requests: 40
env_variables:
  GAE_MEMORY_MB: '4096'
  REDISHOST: '10.237.154.51'
  REDISPORT: '6379'
vpc_access_connector:
  name: projects/treapapp/locations/europe-west1/connectors/treap-vpc